version: "3"
services:
  node:
    container_name: "home_dict_node"
    image: "node:14"
    privileged: false
    user: "node"
    working_dir: /home/node/app
    environment:
      - SERVICE_PROVIDER=vultr
      - NODE_ENV=production
    volumes:
      - ./etc/cert/key.pem:/etc/cert/key.pem
      - ./etc/cert/cert.pem:/etc/cert/cert.pem
      - ./:/home/node/app
    ports:
      - "7443:7443"
    command: "npm run start"
    networks:
      - home_chat

networks:
  home_chat:
    external: true
